try to fix error described below by adding missing module
https://github.com/firebase/firebase-tools/issues/4321

Error: Cannot find module 'cli-color'
  Require stack:
  - /home/runner/work/datatoggle-doc/datatoggle-doc/node_modules/firebase-tools/lib/bin/firebase.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
      at Function.Module._load (node:internal/modules/cjs/loader:769:27)
      at Module.require (node:internal/modules/cjs/loader:996:19)
      at require (node:internal/modules/cjs/helpers:92:18)
      at Object.<anonymous> (/home/runner/work/datatoggle-doc/datatoggle-doc/node_modules/firebase-tools/lib/bin/firebase.js:16:13)
      at Module._compile (node:internal/modules/cjs/loader:1092:14)

  ***